const express = require('express')
const app = express()
const cors = require('cors')
const expressLayout = require("express-ejs-layouts")
app.use(cors())
app.use(express.json())
app.set("view engine","ejs")
app.use(expressLayout)
app.use("/public",express.static("public"))
const recipient = require('./routes/Users')
const general = require('./routes/General')
app.use("/",general)
app.listen(8080,()=>{
    console.log("Server Active And Listening")
})